remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Keith Tzeng'
description: 'Quanta Computer, Inc.'


# Online profiles
dribbble: ''
facebook: ''
twitter: ''


# Advanced settings
plugins:
  - jekyll-remote-theme
